name: Build & Push Image
on:
  push:
    branches:
      - master
    tags:
      - v*
  # All external PRs require approval to run actions
  pull_request: ~

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: set up buildx
        uses: docker/setup-buildx-action@v3
      - name: build etcdmon image
        uses: docker/build-push-action@v6
        with:
          context: .
          load: true
          tags: etcdmon:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Create kind cluster
        run: |
          kind create cluster --config tests/e2e/kind.yaml --kubeconfig ./tests/e2e/kubeconfig.yaml
      - name: Load operator images
        run: |
          kind load docker-image etcdmon:latest
      - uses: actions/setup-go@v5
        with:
          go-version: "^1.22.0"
      - run: go test -timeout 5m ./...

  publish:
    runs-on: ubuntu-latest
    needs: test
    permissions:
      contents: read
      packages: write
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: set up qemu
        # For aarch64 builder support
        uses: docker/setup-qemu-action@v3
      - name: set up buildx
        uses: docker/setup-buildx-action@v3
      - name: log in to registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: extract tags
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      - name: build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
